//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.TalentsFinder.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.TalentsFinder.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BACK {
            get {
                return ResourceManager.GetString("BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading data....
        /// </summary>
        public static string LOADING {
            get {
                return ResourceManager.GetString("LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading talents data....
        /// </summary>
        public static string LOADING_TALENTS {
            get {
                return ResourceManager.GetString("LOADING_TALENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading technologies data....
        /// </summary>
        public static string LOADING_TECH {
            get {
                return ResourceManager.GetString("LOADING_TECH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string LOCALE {
            get {
                return ResourceManager.GetString("LOCALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show talents selected.
        /// </summary>
        public static string MAIN_BUTTON_SHOW {
            get {
                return ResourceManager.GetString("MAIN_BUTTON_SHOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Technology Criteria Search.
        /// </summary>
        public static string MAIN_TITLE {
            get {
                return ResourceManager.GetString("MAIN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria.
        /// </summary>
        public static string MAIN_VIEW_TITLE {
            get {
                return ResourceManager.GetString("MAIN_VIEW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More then 1 year.
        /// </summary>
        public static string MORE_1_YEAR {
            get {
                return ResourceManager.GetString("MORE_1_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More then 10 years.
        /// </summary>
        public static string MORE_10_YEAR {
            get {
                return ResourceManager.GetString("MORE_10_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More then 5 years.
        /// </summary>
        public static string MORE_5_YEAR {
            get {
                return ResourceManager.GetString("MORE_5_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select years of experience.
        /// </summary>
        public static string PICKER_TEXT {
            get {
                return ResourceManager.GetString("PICKER_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh talents data.
        /// </summary>
        public static string REFRESH_TALENTS {
            get {
                return ResourceManager.GetString("REFRESH_TALENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting....
        /// </summary>
        public static string SETTING {
            get {
                return ResourceManager.GetString("SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TALENTS.
        /// </summary>
        public static string TALENTS {
            get {
                return ResourceManager.GetString("TALENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job done !!! Congratulations.
        /// </summary>
        public static string TALENTS_DONE_MESSAGE {
            get {
                return ResourceManager.GetString("TALENTS_DONE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no talents to show !!!!.
        /// </summary>
        public static string TALENTS_EMPTY_MESSAGE {
            get {
                return ResourceManager.GetString("TALENTS_EMPTY_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Talents.
        /// </summary>
        public static string TALENTS_VIEW_TITLE {
            get {
                return ResourceManager.GetString("TALENTS_VIEW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Talents Left.
        /// </summary>
        public static string TALENTS_VIEW_TITLE_COUNT {
            get {
                return ResourceManager.GetString("TALENTS_VIEW_TITLE_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TECHNOLOGIES.
        /// </summary>
        public static string TECHNOLOGIES {
            get {
                return ResourceManager.GetString("TECHNOLOGIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TECHNOLOGY.
        /// </summary>
        public static string TECHNOLOGY {
            get {
                return ResourceManager.GetString("TECHNOLOGY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating data....
        /// </summary>
        public static string UPDATING {
            get {
                return ResourceManager.GetString("UPDATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years old.
        /// </summary>
        public static string YEARS_OLD {
            get {
                return ResourceManager.GetString("YEARS_OLD", resourceCulture);
            }
        }
    }
}
